import type { TechTrend } from "@/lib/types/intelligence";
import type {
  IndustryNews,
  HotTopic,
  KOL,
  Opportunity,
} from "@/lib/types/tech-frontier";

export const mockModuleTechTrends: TechTrend[] = [
  {
    id: "t1",
    topic: "具身智能",
    heatTrend: "surging",
    heatLabel: "+180%",
    ourStatus: "none",
    ourStatusLabel: "未布局",
    gapLevel: "high",
    keyMetric: "清华AIR发布2篇顶会论文",
    aiInsight:
      "建议紧急组建3-5人先导小组，重点关注机器人操作与导航方向。可与清华AIR探讨合作可能性。",
    detail:
      "具身智能是将AI与物理世界交互的关键技术方向。清华AIR在该方向已发布2篇ICRA 2024论文，团队扩至15人。我院在该方向布局为空，存在技术路线踏空风险。",
  },
  {
    id: "t2",
    topic: "多模态大模型",
    heatTrend: "rising",
    heatLabel: "+45%",
    ourStatus: "deployed",
    ourStatusLabel: "已布局",
    gapLevel: "low",
    keyMetric: "GPT-4o引发新一轮研究热潮",
    aiInsight: "我院在该方向已有深厚积累，建议保持投入并加强与产业界合作。",
    detail:
      "多模态大模型整合视觉、语音、文本等多种模态，是大模型发展的重要方向。我院在文本-图像多模态方面有3个在研项目和5篇顶会论文积累。",
  },
  {
    id: "t3",
    topic: "AI Agent",
    heatTrend: "surging",
    heatLabel: "+210%",
    ourStatus: "weak",
    ourStatusLabel: "基础薄弱",
    gapLevel: "medium",
    keyMetric: "OpenAI发布Operator产品",
    aiInsight: "我院有理论基础但缺乏工程化能力，建议引进2名工程化人才。",
    detail:
      "AI Agent是自主完成复杂任务的智能代理系统。OpenAI、Anthropic等公司相继发布Agent产品。我院在强化学习方向有理论积累，但工程化落地能力不足。",
  },
  {
    id: "t4",
    topic: "AI for Science",
    heatTrend: "stable",
    heatLabel: "+12%",
    ourStatus: "deployed",
    ourStatusLabel: "已布局",
    gapLevel: "low",
    keyMetric: "Nature连发3篇AI+生物论文",
    aiInsight:
      "当前布局良好，建议加强跨学科合作，尤其是与生命科学学院的联合课题。",
    detail:
      "AI for Science利用AI加速科学发现的新范式。我院在药物发现、蛋白质结构预测方向有2个在研课题。",
  },
  {
    id: "t5",
    topic: "端侧AI推理",
    heatTrend: "rising",
    heatLabel: "+65%",
    ourStatus: "none",
    ourStatusLabel: "未布局",
    gapLevel: "high",
    keyMetric: "Apple发布端侧AI芯片",
    aiInsight: "存在技术路线空白，但该方向偏硬件，可暂时通过合作方式参与。",
    detail:
      "端侧AI将AI推理从云端迁移到边缘设备，涉及模型压缩、专用芯片等技术。Apple、Qualcomm等公司正大力投入。",
  },
];

export const mockIndustryNews: IndustryNews[] = [
  {
    id: "n1",
    title: "OpenAI完成新一轮融资，估值达3000亿美元",
    source: "Reuters",
    type: "投融资",
    date: "2025-01-10",
    impact: "重大",
    summary: "OpenAI完成由软银领投的新一轮融资，估值达3000亿美元，创下AI领域融资纪录。资金将用于扩大算力基础设施和AGI研究。",
    aiAnalysis: "OpenAI估值飙升反映市场对AGI路线的高度认可。建议关注其技术路线变化，我院在大模型对齐和安全方向可寻求合作窗口。该融资可能引发新一轮人才争夺，需警惕核心研究人员被高薪挖角。",
    relevance: "与我院大模型研究方向高度相关，可探索学术合作机会",
  },
  {
    id: "n2",
    title: "Google正式发布Gemini 2.0，多模态能力大幅提升",
    source: "TechCrunch",
    type: "新产品",
    date: "2025-01-08",
    impact: "重大",
    summary: "Google发布新一代多模态模型Gemini 2.0，在视觉理解、代码生成和推理能力上均有显著突破，支持100万token上下文窗口。",
    aiAnalysis: "Gemini 2.0在多模态基准测试中部分超越GPT-4o。建议我院多模态团队密切跟踪其技术报告，评估我院现有模型的差距。长上下文窗口技术值得重点研究。",
    relevance: "与我院多模态大模型研究直接相关",
  },
  {
    id: "n3",
    title: "字节跳动收购AI芯片设计公司芯驰科技",
    source: "36氪",
    type: "收购",
    date: "2025-01-06",
    impact: "较大",
    summary: "字节跳动以约50亿元收购芯驰科技，加速布局AI推理芯片自研。此举标志着大型互联网公司加速向AI全栈自主化方向发展。",
    aiAnalysis: "字节收购芯片公司表明大厂正加速AI全栈化布局。端侧AI芯片领域我院尚未布局，建议通过产学研合作方式参与。可与字节跳动探讨联合实验室可能性。",
    relevance: "与我院AI芯片方向潜在研究契合",
  },
  {
    id: "n4",
    title: "百度发布文心大模型5.0，首次集成多Agent协作",
    source: "界面新闻",
    type: "新产品",
    date: "2025-01-05",
    impact: "较大",
    summary: "百度发布文心大模型5.0版本，首次内置多Agent协作框架，支持自动化工作流编排，在企业应用场景中表现突出。",
    aiAnalysis: "多Agent协作是我院AI Agent方向的重要落地场景。建议与百度AI研究院对接，探讨在Agent协作框架上的学术合作。该方向可作为我院Agent研究工程化的突破口。",
    relevance: "与我院AI Agent研究方向紧密相关",
  },
  {
    id: "n5",
    title: "国务院发布《人工智能产业高质量发展指导意见》",
    source: "新华社",
    type: "政策",
    date: "2025-01-03",
    impact: "重大",
    summary: "国务院正式发布AI产业发展指导意见，明确提出加大基础研究投入、培育AI人才梯队、推动产学研深度融合等重点任务，配套设立500亿元AI发展专项基金。",
    aiAnalysis: "国家级政策利好明显，500亿专项基金为高校AI研究提供重大机遇。建议立即组织政策解读会，梳理可申报方向。重点关注基础研究和人才培育两个板块的资金申请窗口。",
    relevance: "直接影响我院科研经费申请和学科建设",
  },
];

export const mockHotTopics: HotTopic[] = [
  {
    id: "tp1",
    title: "Scaling Law是否已触及天花板",
    heat: 92,
    maxHeat: 100,
    discussions: 3420,
    trend: "up",
    tags: ["大模型", "理论"],
    summary: "近期多篇论文对Scaling Law的持续有效性提出质疑，认为在特定任务上模型规模增长带来的性能提升正在放缓。OpenAI内部也传出调整策略的消息，社区讨论激烈。",
    aiAnalysis: "该话题直接影响我院大模型研究路线选择。如果Scaling Law收益递减，Small Model和高效推理方向将成为新重点。建议组织学术研讨会深入讨论，评估是否需要调整研究资源配置。",
  },
  {
    id: "tp2",
    title: "World Model与视频生成新范式",
    heat: 87,
    maxHeat: 100,
    discussions: 2180,
    trend: "new",
    tags: ["世界模型", "视频生成"],
    summary: "Sora引发的世界模型讨论持续升温。学术界对物理世界模拟能力的研究快速推进，多个团队发布了结合物理引擎的视频生成模型，引发对AGI路线的新思考。",
    aiAnalysis: "世界模型是AGI研究的潜在关键方向。我院在视觉理解方面有一定积累，可考虑拓展至世界模型领域。建议与计算机视觉团队联合立项，抢占学术制高点。",
  },
  {
    id: "tp3",
    title: "AI安全与对齐研究的紧迫性",
    heat: 78,
    maxHeat: 100,
    discussions: 1560,
    trend: "up",
    tags: ["AI安全", "对齐"],
    summary: "随着模型能力增强，AI安全问题引发广泛关注。Anthropic发布新的安全评估框架，多国政府加速AI监管立法。学术界关于对齐技术的研究论文数量激增。",
    aiAnalysis: "AI安全是国家战略重点方向，经费充裕且竞争相对较小。建议尽快组建AI安全研究小组，可从RLHF改进和模型可解释性两个方向切入。",
  },
  {
    id: "tp4",
    title: "端侧大模型部署与量化技术",
    heat: 71,
    maxHeat: 100,
    discussions: 1230,
    trend: "stable",
    tags: ["模型压缩", "端侧部署"],
    summary: "Apple、Qualcomm等芯片厂商推动端侧AI，模型量化和蒸馏技术成为焦点。1B参数级别模型在手机端达到可用水平，催生新的应用场景和研究课题。",
    aiAnalysis: "端侧部署是模型落地的关键环节。建议与硬件团队合作，在模型压缩和推理优化方向加大投入。可争取手机厂商横向课题。",
  },
  {
    id: "tp5",
    title: "多智能体协作系统设计",
    heat: 85,
    maxHeat: 100,
    discussions: 1890,
    trend: "up",
    tags: ["Agent", "协作"],
    summary: "多Agent系统在复杂任务中展现出超越单Agent的能力。AutoGen、CrewAI等框架获得广泛关注，企业级应用案例开始涌现。学术界关于Agent间通信和协调机制的研究快速增长。",
    aiAnalysis: "该方向与我院AI Agent研究高度契合。建议将多Agent协作作为重点研究方向之一，可结合我院强化学习团队的优势，在协作策略优化方向形成突破。",
  },
];

export const mockKOLs: KOL[] = [
  {
    id: "k1",
    name: "Yann LeCun",
    affiliation: "Meta / NYU",
    hIndex: 168,
    field: "深度学习",
    recentActivity: "公开质疑LLM路线，力推World Model",
    influence: "极高",
    summary: "图灵奖得主，Meta首席AI科学家。近期频繁发声反对纯LLM路线，主张结合世界模型和因果推理，对学术界研究方向有重要引导作用。",
    aiAnalysis: "LeCun的观点值得高度关注。他提出的JEPA架构可能成为下一代AI架构候选方案。建议安排研究团队深入研读其最新论文，评估JEPA方向的布局可能性。",
  },
  {
    id: "k2",
    name: "朱松纯",
    affiliation: "北京大学 / 北京通用人工智能研究院",
    hIndex: 112,
    field: "通用人工智能",
    recentActivity: "发布「通智2.0」通用智能体平台",
    influence: "极高",
    summary: "北京大学讲席教授，通用人工智能研究院院长。其团队在具身智能和认知架构方向处于国内领先地位，「通智」平台已成为学术界标杆。",
    aiAnalysis: "朱松纯团队是具身智能领域国内最重要的合作伙伴候选。建议院长亲自对接，探讨联合培养博士生和共建实验室的可能性。",
  },
  {
    id: "k3",
    name: "唐杰",
    affiliation: "清华大学",
    hIndex: 98,
    field: "知识图谱与大模型",
    recentActivity: "ChatGLM系列模型持续更新，发布GLM-4-Plus",
    influence: "高",
    summary: "清华大学计算机系教授，智谱AI联合创始人。在知识图谱和大模型领域有深厚积累，ChatGLM系列是国内最具影响力的开源大模型之一。",
    aiAnalysis: "唐杰教授团队在产学研结合方面是标杆。建议学习其智谱AI模式，评估我院是否可在特定垂直领域打造类似的产学研平台。",
  },
  {
    id: "k4",
    name: "Ilya Sutskever",
    affiliation: "Safe Superintelligence Inc.",
    hIndex: 132,
    field: "AI安全与超级对齐",
    recentActivity: "创办SSI公司，融资超10亿美元",
    influence: "极高",
    summary: "前OpenAI首席科学家，AlexNet论文共同作者。离开OpenAI后创办专注超级AI安全的公司SSI，引发学术界对AI安全方向的新一轮关注。",
    aiAnalysis: "Sutskever的转向表明AI安全将成为顶级研究者的首选方向。建议我院在AI安全领域提前布局，可尝试联系SSI探讨学术合作。",
  },
  {
    id: "k5",
    name: "鄂维南",
    affiliation: "北京大学 / 普林斯顿大学",
    hIndex: 95,
    field: "AI for Science",
    recentActivity: "发表AI驱动分子动力学新方法，Nature正刊",
    influence: "高",
    summary: "中科院院士，在AI与科学计算交叉领域有深远影响。其Deep Potential方法已成为AI for Science领域的标志性工作。",
    aiAnalysis: "鄂维南院士团队在AI for Science方向是国内翘楚。我院已有相关布局，建议加强与其团队在分子模拟和科学计算方向的合作深度。",
  },
];

export const mockOpportunities: Opportunity[] = [
  {
    id: "o1",
    name: "ICML 2025 特邀报告邀请",
    type: "会议",
    source: "ICML组委会",
    priority: "紧急",
    deadline: "2025-01-20",
    summary: "ICML 2025组委会发来特邀报告邀请，主题为「大模型时代的AI安全与对齐」。这是顶级会议的高规格邀请，需尽快确认是否出席并提交摘要。会议定于7月在维也纳举办。",
    aiAssessment: "ICML特邀报告是提升我院国际影响力的重要机会，建议院长亲自出席或指定顶级教授代表。该报告主题与我院AI安全研究方向契合，可借此机会展示研究成果并拓展国际合作网络。",
    actionSuggestion: "建议3日内确认出席，安排教授准备报告大纲",
  },
  {
    id: "o2",
    name: "华为-高校AI联合实验室共建计划",
    type: "合作",
    source: "华为2012实验室",
    priority: "高",
    deadline: "2025-02-15",
    summary: "华为2012实验室拟与5所高校共建AI联合实验室，涉及大模型训练优化、端侧推理和AI编译器方向。每个联合实验室配套经费约2000万元/年，共建期3年。",
    aiAssessment: "华为联合实验室项目资金充裕且技术方向前沿。我院在大模型训练优化方向有积累，建议重点申报该方向。需注意知识产权条款的谈判，确保学术发表自由度。",
    actionSuggestion: "建议立即成立申报团队，2周内完成项目计划书",
  },
  {
    id: "o3",
    name: "MIT CSAIL学术访问交流项目",
    type: "合作",
    source: "MIT CSAIL",
    priority: "高",
    deadline: "2025-03-01",
    summary: "MIT计算机科学与人工智能实验室发来学术访问邀请，拟开展为期6个月的联合研究计划，方向为多模态学习与机器人控制。可派遣2-3名青年教师及博士生。",
    aiAssessment: "MIT CSAIL是全球顶级AI实验室，此次访问机会对我院青年教师成长和国际化布局具有战略意义。多模态+机器人方向也有助于弥补我院在具身智能方向的空白。",
    actionSuggestion: "建议遴选2名青年骨干教师和3名优秀博士生",
  },
  {
    id: "o4",
    name: "AI赋能教育改革内参选题",
    type: "内参",
    source: "教育部高教司",
    priority: "中",
    deadline: "2025-02-28",
    summary: "教育部高教司征集「AI赋能高等教育改革」内参稿件，拟选编10篇优秀内参报送国务院参考。这是展示我院AI教育实践成果的良好契机。",
    aiAssessment: "内参报送是提升我院在教育系统影响力的重要渠道。建议围绕「AI赋能计算机专业教学改革」主题撰写，结合我院LLM辅助教学试点项目的实际数据和成效。",
    actionSuggestion: "建议指派副院长牵头，1周内完成内参初稿",
  },
  {
    id: "o5",
    name: "国家自然科学基金AI重大专项预申报",
    type: "合作",
    source: "国家自然科学基金委",
    priority: "紧急",
    deadline: "2025-01-25",
    summary: "国家自然科学基金委发布2025年度AI重大研究专项预申报通知，涵盖基础理论、关键技术和应用示范三个板块，单项资助额度最高5000万元。",
    aiAssessment: "重大专项是获取大规模科研经费的核心渠道。建议组织3-5个方向的预申报团队，重点布局AI基础理论（大模型可解释性）和关键技术（高效推理）两个板块。需院长亲自协调跨课题组资源。",
    actionSuggestion: "建议立即召开教授会议讨论申报策略，5日内确定方向",
  },
];
